name: Feelpp CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - develop

jobs:
  feelpp:
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip feelpp')  &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
          matrix:
            TARGET:
              - "ubuntu:22.04"
              - "ubuntu:20.04"
              - "debian:11"
              - "debian:12"
    steps:
      - name: Print
        run: |
          echo "Running on ${{ matrix.TARGET }}"
          echo "Branch ${{ github.event.pull_request && github.head_ref || github.ref_name }}"
          echo "message ${{ github.event.head_commit.message }}"
          text=$(git log -1 --no-merges --pretty=%B)
          echo "text $text"
          echo "message ${{ github.event.commits[0].message }}"
#          echo "${{toJSON(github.event)}}"

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Workaround checkout Needed single revision issue
        run: |
          git submodule foreach 'git rev-parse HEAD > /dev/null 2>&1 || rm -rf $PWD'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build and Test Feelpp
        id: build-feelpp
        run: |
          echo "Building Feelpp for branch ${{ env.BRANCH }}"
          feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  testsuite:
    needs: [feelpp]
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip tests')  &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Run Feelpp Testsuite
        id: test-feelsuite
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh testsuite
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  toolboxes:
    needs: [feelpp]
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip toolboxes')  &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp Toolboxes
        id: build-feeltoolboxes
        if: |
          !contains(github.event.head_commit.message, 'skip toolboxes') &&
          !contains(github.event.head_commit.message, 'skip components')
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh toolboxes
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  mor:
    needs: [toolboxes]
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip mor') &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp MOR
        id: build-feelmor
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh mor
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  python:
    needs: [feelpp,toolboxes,mor]
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip python') &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp Python
        id: build-feelpython
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp-python
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20
