name: Feelpp CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - develop

jobs:
  feelpp_activate:
    runs-on: self-docker
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.HEAD_COMMIT_MESSAGE }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_SHA }}
    - name: Get Head Commit Message
      id: get_head_commit_message
      run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
    - name: Print
      run: |
        echo "Running on ${{ matrix.TARGET }}"
        echo "Branch ${{ github.event.pull_request && github.head_ref || github.ref_name }}"
        echo "message ${{ steps.get_head_commit_message.outputs.HEAD_COMMIT_MESSAGE }}"

  feelpp:
    needs: [feelpp_activate]
    runs-on: self-docker
    if: |
      !contains ( needs.feelpp_activate.outputs.head-commit-message, 'skip feelpp' )  &&
      !contains ( needs.feelpp_activate.outputs.head-commit-message, 'skip components' )
    continue-on-error: false
    timeout-minutes: 600
    strategy:
          matrix:
            TARGET:
              - "ubuntu:22.04"
              - "ubuntu:20.04"
              - "debian:11"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_SHA }}
      - name: Get Head Commit Message
        id: get_head_commit_message
        run: echo "HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"
      - name: Print
        run: |
          echo "Running on ${{ matrix.TARGET }}"
          echo "Branch ${{ github.event.pull_request && github.head_ref || github.ref_name }}"
          echo "message ${{ steps.get_head_commit_message.outputs.HEAD_COMMIT_MESSAGE }}"

      - name: Workaround checkout Needed single revision issue
        run: |
          git submodule foreach 'git rev-parse HEAD > /dev/null 2>&1 || rm -rf $PWD'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build and Test Feelpp
        id: build-feelpp
        run: |
          echo "Building Feelpp for branch ${{ env.BRANCH }}"
          feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  testsuite:
    needs: [feelpp]
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip tests')  &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Run Feelpp Testsuite
        id: test-feelsuite
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh testsuite
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  toolboxes:
    needs: [feelpp]
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip toolboxes')  &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp Toolboxes
        id: build-feeltoolboxes
        if: |
          !contains(github.event.head_commit.message, 'skip toolboxes') &&
          !contains(github.event.head_commit.message, 'skip components')
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh toolboxes
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  mor:
    needs: [toolboxes]
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip mor') &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp MOR
        id: build-feelmor
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh mor
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  python:
    needs: [feelpp,toolboxes,mor]
    runs-on: self-docker
    if: |
      !contains(github.event.head_commit.message, 'skip python') &&
      !contains(github.event.head_commit.message, 'skip components')
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp Python
        id: build-feelpython
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp-python
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20
