name: Feelpp CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - develop

jobs:
  check_skip:
    runs-on: self-docker
    outputs:
        check_skip_components: ${{ steps.check_skip_components.outputs.SKIP_COMPONENT }}
        check_skip_feelpp: ${{ steps.check_skip_components.outputs.SKIP_FEELPP }}
        check_skip_tests: ${{ steps.check_skip_components.outputs.SKIP_TESTS }}
        check_skip_toolboxes: ${{ steps.check_skip_components.outputs.SKIP_TOOLBOXES }}
        check_skip_mor: ${{ steps.check_skip_components.outputs.SKIP_MOR }}
        check_skip_python: ${{ steps.check_skip_components.outputs.SKIP_PYTHON }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_SHA }}
    - name: Check if skip components
      id: check_skip_components
      run: |
        if [[ $(git show -s --format=%s) =~ "skip components" ]]; then
          echo "SKIP_COMPONENT=true" >> $GITHUB_OUTPUT
        else
          echo "SKIP_COMPONENT=false" >> $GITHUB_OUTPUT
        fi
        if [[ $(git show -s --format=%s) =~ "skip feelpp" ]]; then
          echo "SKIP_FEELPP=true" >> $GITHUB_OUTPUT
        else
          echo "SKIP_FEELPP=false" >> $GITHUB_OUTPUT
        fi
        if [[ $(git show -s --format=%s) =~ "skip tests" ]]; then
          echo "SKIP_TESTS=true" >> $GITHUB_OUTPUT
        else
          echo "SKIP_TESTS=false" >> $GITHUB_OUTPUT
        fi
        if [[ $(git show -s --format=%s) =~ "skip toolboxes" ]]; then
          echo "SKIP_TOOLBOXES=true" >> $GITHUB_OUTPUT
        else
          echo "SKIP_TOOLBOXES=false" >> $GITHUB_OUTPUT
        fi
        if [[ $(git show -s --format=%s) =~ "skip mor" ]]; then
          echo "SKIP_MOR=true" >> $GITHUB_OUTPUT
        else
          echo "SKIP_MOR=false" >> $GITHUB_OUTPUT
        fi
        if [[ $(git show -s --format=%s) =~ "skip python" ]]; then
          echo "SKIP_PYTHON=true" >> $GITHUB_OUTPUT
        else
          echo "SKIP_PYTHON=false" >> $GITHUB_OUTPUT
        fi

  feelpp:
    needs: [check_skip]
    runs-on: self-docker
    if: |
      needs.check_skip.outputs.check_skip_components == 'false' &&
      needs.check_skip.outputs.check_skip_feelpp == 'false'
    continue-on-error: false
    timeout-minutes: 600
    strategy:
          matrix:
            TARGET:
              - "ubuntu:22.04"
              - "ubuntu:20.04"
              - "debian:11"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Workaround checkout Needed single revision issue
        run: |
          git submodule foreach 'git rev-parse HEAD > /dev/null 2>&1 || rm -rf $PWD'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build and Test Feelpp
        id: build-feelpp
        run: |
          echo "Building Feelpp for branch ${{ env.BRANCH }}"
          feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  testsuite:
    needs: [check_skip,feelpp]
    runs-on: self-docker
    if: |
      always() &&
      !contains ( needs.*.result, 'failure') &&
      !contains ( needs.*.result, 'cancelled') &&
      needs.check_skip.outputs.check_skip_components == 'false' &&
      needs.check_skip.outputs.check_skip_tests == 'false'
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Run Feelpp Testsuite
        id: test-feelsuite
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh testsuite
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  toolboxes:
    needs: [check_skip,feelpp]
    runs-on: self-docker
    if: |
      always() &&
      !contains ( needs.*.result, 'failure') &&
      !contains ( needs.*.result, 'cancelled') &&
      needs.check_skip.outputs.check_skip_components == 'false' &&
      needs.check_skip.outputs.check_skip_toolboxes == 'false'
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp Toolboxes
        id: build-feeltoolboxes
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh toolboxes
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  mor:
    needs: [check_skip,toolboxes]
    runs-on: self-docker
    if: |
      always() &&
      !contains ( needs.*.result, 'failure') &&
      !contains ( needs.*.result, 'cancelled') &&
      needs.check_skip.outputs.check_skip_components == 'false' &&
      needs.check_skip.outputs.check_skip_mor == 'false'
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp MOR
        id: build-feelmor
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh mor
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20

  python:
    needs: [check_skip,feelpp,toolboxes,mor]
    runs-on: self-docker
    if: |
      always() &&
      !contains ( needs.*.result, 'failure') &&
      !contains ( needs.*.result, 'cancelled') &&
      needs.check_skip.outputs.check_skip_components == 'false' &&
      needs.check_skip.outputs.check_skip_python == 'false'
    continue-on-error: false
    timeout-minutes: 600
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp Python
        id: build-feelpython
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp-python
        env:
          TARGET: ${{ matrix.TARGET }}
          BRANCH: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
          CR_PAT: ${{ secrets.CR_PAT }}
          CR_LOGIN: ${{ secrets.CR_LOGIN }}
          JOBS: 20
