name: CI

on: 
  schedule:
    # run every day at 2am  
    - cron: '0 2 * * 0' # fedora 36
    - cron: '0 2 * * 1' # kinetic
    - cron: '0 2 * * 2' # in the future fedora 37
    - cron: '0 2 * * 3' # debian sid
    - cron: '0 2 * * 4'
    - cron: '0 2 * * 5'
    - cron: '0 2 * * 6'


jobs:

  activate:
    runs-on: self-ubuntu-20.04
    if: |
      github.repository == 'feelpp/feelpp' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  build:
    strategy:
      fail-fast: false
      matrix: 
        include:
          - {flavor: fedora, version: "36", dotw: 0}
    name: ${{ matrix.flavor }}-${{ matrix.version }}
    env:
      os: ${{ matrix.flavor }}-${{ matrix.version }}
    runs-on: self-docker-${{ env.os }}
    if: github.event.schedule == format('0 2 * * {0}', ${{ matrix.dotw }} )
    needs: activate
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configure feelpp
      run: |
        . /etc/profile.d/modules.sh
        module load mpi/openmpi-x86_64
        mpicxx -v
        cmake --preset feelpp
#    - name: Build feelpp
#      run: cmake --build --preset feelpp -j 10
#    - name: Test feelpp
#      run: ctest --preset feelpp -j 2
