name: Feelpp CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - develop

jobs:
  feelpp:
    runs-on: self-docker
    continue-on-error: false
    strategy:
          matrix:
            TARGET:
              - "ubuntu:22.04"
              - "ubuntu:20.04"
              - "debian:11"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build and Test Feelpp
        id: build-feelpp
        if: ${{ !contains(github.event.head_commit.message, 'skip feelpp')  && !contains(github.event.head_commit.message, 'skip components')}}
        run: |
          echo "REF=${{ github.event.pull_request && github.head_ref || github.ref_name }}" >> $GITHUB_ENV
          echo "result REF=$REF"
          echo "Building Feelpp for branch ${{ github.ref_name }}"
          feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
        env:
          TARGET: ${{ matrix.TARGET }}

  testsuite:
    needs: [feelpp]
    runs-on: self-docker 
    continue-on-error: false
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Run Feelpp Testsuite
        if: ${{ !contains(github.event.head_commit.message, 'skip tests') && !contains(github.event.head_commit.message, 'skip components') }}
        id: test-feelsuite
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh testsuite
        env:
          TARGET: ${{ matrix.TARGET }}

  toolboxes:
    needs: [feelpp]
    runs-on: self-docker
    continue-on-error: false
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp Toolboxes
        id: build-feeltoolboxes
        if: ${{ !contains(github.event.head_commit.message, 'skip toolboxes') && !contains(github.event.head_commit.message, 'skip components') }}
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh toolboxes
        env:
          TARGET: ${{ matrix.TARGET }}

  mor:
    needs: [toolboxes]
    runs-on: self-docker
    if: ${{ !contains(github.event.head_commit.message, 'skip mor') && !contains(github.event.head_commit.message, 'skip components') }}
    continue-on-error: false
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp MOR
        id: build-feelmor
        run: |
          if [[ ${{ github.event.head_commit.message }} =~ skip\ mor.*|skip\ components.* ]]; then
            exit 0
          fi
          TARGET=${{ matrix.TARGET }}
          feelpp/tools/scripts/buildkite/install-feelpp.sh mor
        env:
          TARGET: ${{ matrix.TARGET }}

  python:
    needs: [feelpp,toolboxes,mor]
    runs-on: self-docker
    if: ${{ !contains(github.event.head_commit.message, 'skip python') && !contains(github.event.head_commit.message, 'skip components') }}
    continue-on-error: false
    strategy:
        matrix:
            TARGET:
              - "ubuntu:22.04"
              - "debian:12"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            submodules: recursive

      - name: Build Feelpp Python
        id: build-feelpython
        run: |
          feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp-python
        env:
          TARGET: ${{ matrix.TARGET }}
