name: Manual CI

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Distribution flavor'     
        required: true
        default: 'fedora'
        options: ['ubuntu', 'debian', 'fedora']
      version:
        description: 'Version of the distribution'  
        required: true
        default: "36"
        options: ['20.04', '22.04', '22.10', '10', '11', 'testing', 'sid', '36', '37']

jobs:

  activate:
    runs-on: self-ubuntu-20.04
    if: |
      github.repository == 'feelpp/feelpp' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ok go

  build:
    env:
      os: ${{ inputs.flavor }}-${{ inputs.version }}
    name: ${{ inputs.flavor }}-${{ inputs.version }}
    runs-on: self-docker-${{ inputs.flavor }}-${{ inputs.version }}
    needs: activate
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configure feelpp
      run: cmake --preset feelpp
    - name: Build feelpp
      run: cmake --build --preset feelpp -j 10
    - name: Test feelpp
      run: ctest --preset feelpp -j 2
    - name: Install feelpp
      run: cmake --install --preset feelpp
