on:
    workflow_call:
        inputs:
            dist: 
                required: true
                type: string
                default: "jammy"
            flavor: 
                required: true
                type: string 
                default: "ubuntu"

jobs:
    activate:
        if: ${{ github.event.inputs.dist == 'jammy' && github.event.inputs.flavor == 'ubuntu' }}
        runs-on: self-pkg
        steps:
        - run: echo ok go $FLAVOR - $DIST 
          shell: bash
          env:
            DIST: ${{ github.event.inputs.dist }}
            FLAVOR: ${{ github.event.inputs.flavor }}
    build:
        needs: activate
        runs-on: self-pkg
        env:
            DIST: ${{ github.event.inputs.dist }}
            FLAVOR: ${{ github.event.inputs.flavor }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Build Feelpp package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ feelpp.*|skip\ components.*|skip\ $DIST.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg.sh
          env:
            COMPONENT: feelpp

        - name: Publish Feelpp package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ feelpp.*|skip\ components.*|skip\ $DIST.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg_publish.sh
          env:
            COMPONENT: feelpp

        - name: Build  Feelpp toolboxes package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ toolboxes.*|skip\ components.*|skip\ $DIST.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg.sh
          env:
            COMPONENT: feelpp-toolboxes

        - name: Publish Feelpp toolboxes package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ toolboxes.*|skip\ components.*|skip\ $DIST.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg_publish.sh
          env:
            COMPONENT: feelpp-toolboxes

        - name: Build Feelpp MOR package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ mor.*|skip\ components.*|skip\ $DIST.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg.sh
          env:
            COMPONENT: feelpp-mor

        - name: Publish Feelpp MOR package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ mor.*|skip\ components.*|skip\ $DIST.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg_publish.sh
          env:
            COMPONENT: feelpp-mor

        - name: Build Feelpp Python package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ python.*|skip\ components.*|skip\ $DIST.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg.sh
          env:
            COMPONENT: feelpp-python

        - name: Publish Feelpp Python package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ python.*|skip\ components.*|skip\ $DIST.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg_publish.sh
          env:
            COMPONENT: feelpp-python

        - name: Build and publish Feelpp Docker package
          run: |
            if [[ ${{ github.event.head_commit.message }} =~ skip\ docker.* ]]; then
            exit 0
            fi
            feelpp/tools/scripts/pkg/feelpp_pkg_docker.sh

