name: Feelpp PKG Reusable Workflow
on:
    workflow_call:
        inputs:
            flavor:
                description: 'Flavor of the distribution'
                required: true
                type: string
                default: "ubuntu"
            dist:
                description: 'Name of the distribution'
                required: true
                type: string
                default: "jammy"
            version:
                description: 'Version of Feel++ packages'
                required: true
                type: string
            skip:
                description: 'Skip docker build'
                required: false
                type: boolean
                default: false

jobs:

  docker:
    if: ${{ !github.event.inputs.skip }}
    runs-on: self-docker
    strategy:
      fail-fast: false
      matrix:
        include:
          - {
              service: "feelpp",
              flavor: "${{ github.event.inputs.flavor }}",
              dist: "${{ github.event.inputs.dist }}",
              version: "${{ github.event.inputs.version }}",
              tag: "v${{ github.event.inputs.version }}-${{ github.event.inputs.dist }}",
              dockerfile: "Dockerfile",
            }
          - {
              service: "feelpp-dev",
              flavor: "${{ github.event.inputs.flavor }}",
              dist: "${{ github.event.inputs.dist }}",
              version: "${{ github.event.inputs.version }}",
              tag: "v${{ github.event.inputs.version }}-${{ github.event.inputs.dist }}",
              dockerfile: "Dockerfile",
            }
    name: Build and Push feelpp/${{ matrix.service }}:${{ matrix.tag }}

    steps:
    - uses: actions/checkout@v4
      with:
#        lfs: true
        token: ${{ secrets.CR_PAT }}
        submodules: recursive
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Build ${{ matrix.service }}:${{ matrix.tag }}
      uses: docker/build-push-action@v4
      if: ${{ matrix.service == 'feelpp' }}
      with:
        context: ./${{ matrix.service }}/
        tags: ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.tag }},ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.dist }}
        file: ${{ matrix.service }}/${{ matrix.dockerfile }}
        build-args: |
          IMAGE=${{ matrix.flavor }}:${{ matrix.dist }}
          FLAVOR=${{ matrix.flavor }}
          DIST=${{ matrix.dist }}
          VERSION=${{ matrix.version }}
        push: true
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}
    -
      name: Build ${{ matrix.service }}:${{ matrix.tag }}
      if: ${{ matrix.service == 'feelpp-dev' }}
      uses: docker/build-push-action@v3
      with:
        context: ./${{ matrix.service }}
        tags: ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.tag }},ghcr.io/feelpp/${{ matrix.service }}:${{ matrix.dist }}
        file: ${{ matrix.service }}/${{ matrix.dockerfile }}
        build-args: TAG=${{ matrix.tag }}
        push: true
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.CR_PAT }}