name: Feelpp PKG CI

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      parallel:
        description: 'Number of parallel jobs'
        required: false
        default: "20"
        type: string
      skip:
        description: 'Skip build'
        required: false
        default: "false"
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { distro: 'ubuntu/jammy', flavor: ubuntu, dist: jammy, version: '22.04' }
          - { distro: 'ubuntu/focal', flavor: ubuntu, dist: focal, version: '20.04' }
          - { distro: 'ubuntu/lunar', flavor: ubuntu, dist: lunar, version: '23.04' }
          - { distro: 'ubuntu/kinetic', flavor: ubuntu, dist: kinetic, version: '22.10' }
          - { distro: 'debian/bookwork', flavor: debian, dist: bookworm, version: '12' }
          - { distro: 'debian/bullseye', flavor: debian, dist: bullseye, version: '11' }
          - { distro: 'debian/testing', flavor: debian, dist: testing, version: '13' }
          - { distro: 'debian/sid', flavor: debian, dist: sid, version: 'unstable' }
    uses: ./.github/workflows/pkg-dist.yml
    with:
        dist: ${{ matrix.dist }}
        flavor: ${{ matrix.flavor }}
        parallel: ${{ github.event.inputs.parallel }}
        skip: ${{ github.event.inputs.skip }}
    secrets: inherit

